global:
  resolve_timeout: 5m

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${SMTP_FROM}'                 
  smtp_auth_username: '${SMTP_USERNAME}'    
  smtp_auth_password: '${SMTP_PASSWORD}'    
  smtp_require_tls: true                    

route:
  receiver: default-receiver
  group_by: ['alertname', 'severity', 'instance']
  group_wait: 30s                           
  group_interval: 5m                        
  repeat_interval: 1h                       

  routes:
    - match:
        severity: critical
      receiver: critical-receiver

    - match:
        severity: warning
      receiver: warning-receiver

    - match_re:
        severity: "info|notice"
      receiver: default-receiver

receivers:
  - name: default-receiver
    email_configs:
      - to: '${SMTP_TO}'
        send_resolved: true
        subject: "[DEFAULT] {{ .CommonLabels.alertname }} ({{ .Status }})"
        html: |
          <b>{{ .CommonLabels.alertname }}</b><br>
          Severity: {{ .CommonLabels.severity }}<br>
          Instance: {{ .CommonLabels.instance }}<br>
          Summary: {{ .CommonAnnotations.summary }}<br>
          Description: {{ .CommonAnnotations.description }}

  - name: critical-receiver
    email_configs:
      - to: '${SMTP_TO}'
        send_resolved: true
        subject: "[CRITICAL] {{ .CommonLabels.alertname }} ({{ .Status }})"
        html: |
          <b>Critical Alert</b><br>
          Summary: {{ .CommonAnnotations.summary }}<br>
          Description: {{ .CommonAnnotations.description }}<br>
          Instance: {{ .CommonLabels.instance }}

  - name: warning-receiver
    email_configs:
      - to: '${SMTP_TO}'
        send_resolved: true
        subject: "[WARNING] {{ .CommonLabels.alertname }} ({{ .Status }})"
        html: |
          <b>Warning Alert</b><br>
          Summary: {{ .CommonAnnotations.summary }}<br>
          Description: {{ .CommonAnnotations.description }}<br>
          Instance: {{ .CommonLabels.instance }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'instance']
