global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: dev
    region: ap-southeast

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'demo-app-first'
    metrics_path: /metrics
    static_configs:
      - targets: ['demo-app-first:8001']
        labels:
          service: flask-api
          group: demo-services

  - job_name: 'demo-app-second'
    metrics_path: /metrics
    static_configs:
      - targets: ['demo-app-second:8002']
        labels:
          service: flask-api
          group: demo-services

  - job_name: 'demo-app-third'
    metrics_path: /metrics
    static_configs:
      - targets: ['demo-app-third:8003']
        labels:
          service: flask-api
          group: demo-services

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

rule_files:
  - "alert.rules.yml"  
